export const badgeClass = {
    ok: "bg-green",
    slow: "bg-gray",
    "very bad": "bg-danger",
    undefined: "hidden",
    null: "hidden",
    replace: "bg-red",
    paused: 'bg-yellow',
    logout: 'bg-pink',
    suspended: 'bg-brown',
    active: 'bg-ok',
    waiting: 'bg-blue',
    cooldown: 'bg-purple',
    failed: 'bg-danger',
    proxy_failed: 'bg-danger',
    arkose: 'bg-red',
};
